"""Provides the microcontroller interface classes, configuration dataclasses, and the log processing pipeline."""

from .interface import ModuleInterface, MicroControllerInterface, evaluate_port
from .dataclasses import (
    EXTRACTION_CONFIGURATION_FILENAME,
    MICROCONTROLLER_MANIFEST_FILENAME,
    ExtractionConfig,
    ModuleSourceData,
    KernelExtractionConfig,
    ModuleExtractionConfig,
    MicroControllerManifest,
    MicroControllerSourceData,
    ControllerExtractionConfig,
    create_extraction_config,
    write_microcontroller_manifest,
)
from .log_processing import (
    FEATHER_SUFFIX,
    TRACKER_FILENAME,
    LOG_ARCHIVE_SUFFIX,
    EXTRACTION_JOB_NAME,
    KERNEL_FEATHER_INFIX,
    MODULE_FEATHER_INFIX,
    PARALLEL_PROCESSING_THRESHOLD,
    MICROCONTROLLER_DATA_DIRECTORY,
    execute_job,
    prepare_tracker,
    find_log_archive,
    generate_job_ids,
    resolve_recording_roots,
    run_log_processing_pipeline,
)

__all__ = [
    "EXTRACTION_CONFIGURATION_FILENAME",
    "EXTRACTION_JOB_NAME",
    "FEATHER_SUFFIX",
    "KERNEL_FEATHER_INFIX",
    "LOG_ARCHIVE_SUFFIX",
    "MICROCONTROLLER_DATA_DIRECTORY",
    "MICROCONTROLLER_MANIFEST_FILENAME",
    "MODULE_FEATHER_INFIX",
    "PARALLEL_PROCESSING_THRESHOLD",
    "TRACKER_FILENAME",
    "ControllerExtractionConfig",
    "ExtractionConfig",
    "KernelExtractionConfig",
    "MicroControllerInterface",
    "MicroControllerManifest",
    "MicroControllerSourceData",
    "ModuleExtractionConfig",
    "ModuleInterface",
    "ModuleSourceData",
    "create_extraction_config",
    "evaluate_port",
    "execute_job",
    "find_log_archive",
    "generate_job_ids",
    "prepare_tracker",
    "resolve_recording_roots",
    "run_log_processing_pipeline",
    "write_microcontroller_manifest",
]
