"""Provides the centralized interface for exchanging commands and data between Arduino and Teensy microcontrollers and
host-computers.

See the `documentation <https://ataraxis-communication-interface-api.netlify.app/>`_ for the description of
available assets. See the `source code repository <https://github.com/Sun-Lab-NBB/ataraxis-communication-interface>`_
for more details.

Authors: Ivan Kondratyev (Inkaros), Jacob Groner (Jgroner11)
"""

from .communication import (
    ModuleData,
    ModuleState,
    SerialProtocols,
    SerialPrototypes,
    MQTTCommunication,
)
from .orchestration import (
    CONTROLLER_EXTRACTION_JOB_NAME,
    CONTROLLER_EXTRACTION_JOB_CORES,
    JobSizing,
    JobSource,
    JobUniverse,
    execute_job,
    resolve_jobs,
    size_archive_job,
    find_kernel_paths,
    find_module_paths,
    parse_kernel_path,
    parse_module_path,
    resolve_kernel_path,
    resolve_module_path,
    run_log_processing_pipeline,
)
from .microcontroller import (
    MAXIMUM_CUSTOM_STATUS_CODE,
    MINIMUM_CUSTOM_STATUS_CODE,
    EXTRACTION_CONFIGURATION_FILENAME,
    MICROCONTROLLER_MANIFEST_FILENAME,
    ModuleInterface,
    ExtractionConfig,
    ModuleSourceData,
    KernelStatusCodes,
    ModuleStatusCodes,
    KernelCommandCodes,
    ExtractedDataColumns,
    TransportStatusCodes,
    KernelExtractionConfig,
    ModuleExtractionConfig,
    MicroControllerManifest,
    CommunicationStatusCodes,
    MicroControllerInterface,
    MicroControllerSourceData,
    ControllerExtractionConfig,
    MicroControllerInformation,
    get_event_data,
    partition_events,
    get_event_timestamps,
    create_extraction_config,
    discover_microcontrollers,
    write_microcontroller_manifest,
)

__all__ = [
    "CONTROLLER_EXTRACTION_JOB_CORES",
    "CONTROLLER_EXTRACTION_JOB_NAME",
    "EXTRACTION_CONFIGURATION_FILENAME",
    "MAXIMUM_CUSTOM_STATUS_CODE",
    "MICROCONTROLLER_MANIFEST_FILENAME",
    "MINIMUM_CUSTOM_STATUS_CODE",
    "CommunicationStatusCodes",
    "ControllerExtractionConfig",
    "ExtractedDataColumns",
    "ExtractionConfig",
    "JobSizing",
    "JobSource",
    "JobUniverse",
    "KernelCommandCodes",
    "KernelExtractionConfig",
    "KernelStatusCodes",
    "MQTTCommunication",
    "MicroControllerInformation",
    "MicroControllerInterface",
    "MicroControllerManifest",
    "MicroControllerSourceData",
    "ModuleData",
    "ModuleExtractionConfig",
    "ModuleInterface",
    "ModuleSourceData",
    "ModuleState",
    "ModuleStatusCodes",
    "SerialProtocols",
    "SerialPrototypes",
    "TransportStatusCodes",
    "create_extraction_config",
    "discover_microcontrollers",
    "execute_job",
    "find_kernel_paths",
    "find_module_paths",
    "get_event_data",
    "get_event_timestamps",
    "parse_kernel_path",
    "parse_module_path",
    "partition_events",
    "resolve_jobs",
    "resolve_kernel_path",
    "resolve_module_path",
    "run_log_processing_pipeline",
    "size_archive_job",
    "write_microcontroller_manifest",
]
