from typing import Any, Literal
from pathlib import Path
from threading import Lock, Thread
from dataclasses import field, dataclass

from mcp.server.fastmcp import FastMCP

from .dataclasses import (
    MICROCONTROLLER_MANIFEST_FILENAME as MICROCONTROLLER_MANIFEST_FILENAME,
    ExtractionConfig as ExtractionConfig,
    ModuleSourceData as ModuleSourceData,
    KernelExtractionConfig as KernelExtractionConfig,
    ModuleExtractionConfig as ModuleExtractionConfig,
    MicroControllerManifest as MicroControllerManifest,
    ControllerExtractionConfig as ControllerExtractionConfig,
    write_microcontroller_manifest as write_microcontroller_manifest,
)
from .communication import MQTTCommunication as MQTTCommunication
from .log_processing import (
    FEATHER_SUFFIX as FEATHER_SUFFIX,
    TRACKER_FILENAME as TRACKER_FILENAME,
    LOG_ARCHIVE_SUFFIX as LOG_ARCHIVE_SUFFIX,
    EXTRACTION_JOB_NAME as EXTRACTION_JOB_NAME,
    KERNEL_FEATHER_INFIX as KERNEL_FEATHER_INFIX,
    MODULE_FEATHER_INFIX as MODULE_FEATHER_INFIX,
    PARALLEL_PROCESSING_THRESHOLD as PARALLEL_PROCESSING_THRESHOLD,
    MICROCONTROLLER_DATA_DIRECTORY as MICROCONTROLLER_DATA_DIRECTORY,
    execute_job as execute_job,
    prepare_tracker as prepare_tracker,
    find_log_archive as find_log_archive,
    generate_job_ids as generate_job_ids,
    resolve_recording_roots as resolve_recording_roots,
)
from .microcontroller_interface import _evaluate_port as _evaluate_port

mcp: FastMCP
_WORKER_SCALING_FACTOR: int
_WORKER_MULTIPLE: int
_RESERVED_CORES: int
_MINIMUM_ROWS_FOR_INTERVALS: int
_UNIDENTIFIED_CONTROLLER_ID: int

@dataclass(slots=True)
class _PendingJob:
    log_directory: Path
    output_directory: Path
    tracker_path: Path
    job_id: str
    source_id: str
    config_path: Path
    @property
    def dispatch_key(self) -> tuple[str, str]: ...

@dataclass(slots=True)
class _ActiveGroup:
    source_id: str
    jobs: list[_PendingJob]
    workers: int
    thread: Thread

@dataclass(slots=True)
class _JobExecutionState:
    all_jobs: dict[tuple[str, str], _PendingJob] = field(default_factory=dict)
    pending_queue: list[_PendingJob] = field(default_factory=list)
    active_groups: list[_ActiveGroup] = field(default_factory=list)
    job_message_counts: dict[tuple[str, str], int] = field(default_factory=dict)
    worker_budget: int = ...
    lock: Lock = field(default_factory=Lock)
    manager_thread: Thread | None = ...
    canceled: bool = ...

_job_execution_state: _JobExecutionState | None

def list_microcontrollers(baudrate: int = 115200) -> str: ...
def check_mqtt_broker(host: str = "127.0.0.1", port: int = 1883) -> str: ...
def assemble_log_archives_tool(
    log_directory: str, *, remove_sources: bool = True, verify_integrity: bool = False
) -> dict[str, Any]: ...
def read_microcontroller_manifest_tool(manifest_path: str) -> dict[str, Any]: ...
def write_microcontroller_manifest_tool(
    log_directory: str, controller_id: int, controller_name: str, modules: list[dict[str, Any]]
) -> dict[str, Any]: ...
def discover_microcontroller_data_tool(root_directory: str) -> dict[str, Any]: ...
def read_extraction_config_tool(config_path: str) -> dict[str, Any]: ...
def write_extraction_config_tool(config_path: str, controllers: list[dict[str, Any]]) -> dict[str, Any]: ...
def validate_extraction_config_tool(config_path: str, manifest_path: str | None = None) -> dict[str, Any]: ...
def prepare_log_processing_batch_tool(
    log_directories: list[str], source_ids: list[str], output_directories: list[str], config_path: str
) -> dict[str, Any]: ...
def execute_log_processing_jobs_tool(jobs: list[dict[str, str]], *, worker_budget: int = -1) -> dict[str, Any]: ...
def get_log_processing_status_tool() -> dict[str, Any]: ...
def get_log_processing_timing_tool() -> dict[str, Any]: ...
def cancel_log_processing_tool() -> dict[str, Any]: ...
def reset_log_processing_jobs_tool(tracker_path: str, source_ids: list[str] | None = None) -> dict[str, Any]: ...
def get_batch_status_overview_tool(root_directory: str) -> dict[str, Any]: ...
def verify_processing_output_tool(output_directory: str) -> dict[str, Any]: ...
def query_extracted_events_tool(feather_files: list[str], max_sample_rows: int = 10) -> dict[str, Any]: ...
def clean_log_processing_output_tool(output_directories: list[str]) -> dict[str, Any]: ...
def run_server(transport: Literal["stdio", "sse", "streamable-http"] = "stdio") -> None: ...
def run_mcp_server() -> None: ...
def _read_tracker_status(tracker_path: Path) -> dict[str, Any]: ...
def _derive_tracker_status(summary: dict[str, Any]) -> str: ...
def _group_jobs_by_tracker(state: _JobExecutionState) -> dict[Path, list[_PendingJob]]: ...
def _scan_archive_source_ids(directory: Path) -> list[str]: ...
def _resolve_log_dir_roots(log_dir_paths: list[Path]) -> dict[Path, Path]: ...
def _probe_archive_message_count(job: _PendingJob) -> int: ...
def _compute_sqrt_minimum(message_count: int) -> int: ...
def _clean_single_output(output_directory: str) -> dict[str, Any]: ...
def _group_worker(jobs: list[_PendingJob], workers: int, state: _JobExecutionState) -> None: ...
def _job_execution_manager() -> None: ...
def _analyze_single_event_feather(feather_file: str, max_sample_rows: int) -> dict[str, Any]: ...
