from typing import Literal

from _typeshed import Incomplete

from .communication import MQTTCommunication as MQTTCommunication
from .microcontroller_interface import _evaluate_port as _evaluate_port

mcp: Incomplete

def list_microcontrollers(baudrate: int = 115200) -> str: ...
def check_mqtt_broker(host: str = "127.0.0.1", port: int = 1883) -> str: ...
def run_server(transport: Literal["stdio", "sse", "streamable-http"] = "stdio") -> None: ...
def run_mcp_server() -> None: ...
