from queue import Queue
from typing import Any

import paho.mqtt.client as mqtt

class MQTTCommunication:
    _ip: str
    _port: int
    _connected: bool
    _monitored_topics: tuple[str, ...]
    _output_queue: Queue
    _client: mqtt.Client
    def __init__(
        self, ip: str = "127.0.0.1", port: int = 1883, monitored_topics: tuple[str, ...] | None = None
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __del__(self) -> None: ...
    def _on_message(self, _client: mqtt.Client, _userdata: Any, message: mqtt.MQTTMessage) -> None: ...
    def connect(self) -> None: ...
    def send_data(self, topic: str, payload: str | bytes | bytearray | float | None = None) -> None: ...
    @property
    def has_data(self) -> bool: ...
    def get_data(self) -> tuple[str, bytes] | None: ...
    def disconnect(self) -> None: ...
